### ISSUE TITLE
ArenaPlayerEnterMatchEvent.getCompetition() returns null

### ISSUE THREAD

**Issue by blablubbabc** [BattlePlugins/BattleArena#12]
This is not a critical issue for my usecase, but I thought I report it anyways, in case this is not intended:

Code to reproduce:
@EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
void onMatchJoin(ArenaPlayerEnterMatchEvent event) {
    // event.getCompetition() returns null here
}

Haven't tested if changing the event priority makes a difference.

**Comment by lDucks** [comment]
@clovisd any word? Is this resolved?

**Comment by Europia79** [comment]
@lDucks Does Alkarin have a written specification somewhere ? 

You see... this is really the crux of the issue: Is it intentional ?

Is this done intentionally as part of the design ? Or is it a bug ?

I think either CompetitionEvent was extended without regard to the consequences, or someone forgot to use the comeptition object's ```.callEvent()``` method, which sets the competition field before calling the event.

I will have to see if the competition object was even constructed and obtainable at this point.

We will have to listen to this event (ArenaPlayerEnterMatchEvent), and MatchCreatedEvent, and see which one is fired first. If MatchCreatedEvent is fired first, then it should make this an easier fix. However, if MatchCreatedEvent is fired after ArenaPlayerEnterMatchEvent... then it won't be possible to immediately fix it without some major code refactoring.

**Comment by lDucks** [comment]
@Europia79 I have no clue what alkarin's specifications are/were. Seeing as he is no longer an active part of the project, it would be safe to make your own decision on how you would like this event to function. You're the main developer, if you see disagree with or don't understand alkarin's intentions, you should feel free to change things the way you feel they'd work best.

**Comment by Europia79** [comment]
i just debugged this. ```ArenaPlayerenterMatchEvent``` is fired before ```MatchCreatedEvent```... so it's not currently possible for the ```ArenaPlayerEnterMatchEvent``` to include ```getCompetition()``` because it isn't even created yet.

i believe ```ArenaPlayerEnterMatchEvent``` is mis-named... Maybe a better name would be ```ArenaPlayerEnterQueueEvent``` or ```ArenaPlayerEnterQueueBeforeMatchCreationEvent```

>  I have no clue what alkarin's specifications are/were. Seeing as he is no longer an active part of the project, it would be safe to make your own decision on how you would like this event to function. You're the main developer, if you see disagree with or don't understand alkarin's intentions, you should feel free to change things the way you feel they'd work best.

gotcha. I prefer to discuss major changes with Zach first... To get his opinion. And because I like to err on the side of caution. I have to go for now, but for this specific case, i'll have to contemplate some solutions and discuss them with you and Zach later. It might turn out to be a simple name-change... And moving the location of where this enter is fired (to the correct location so that ```getCompetition()``` does not return null.
