### ISSUE TITLE
Loosing inventory problems

### ISSUE THREAD

**Issue by JoseLu1200** [BattlePlugins/BattleArena#127]
My players are reporting me all the time that they are loosing their inventories, because when they finish a match, the plugin does not return the inventory that they had before playing, when I look at the inventory folder, the inventories have been saved but have not been returned to the player, this happens 1 in 10 times approximately

**Comment by supawiz6991** [comment]
I apologize that this went unanswered for almost a year. Its tough to say what the cause of this issue is... generally I don't hear about inventory loss all that much. Normally when we do hear about it, its either an issue with an inventory management plugin, trying to manipulate inventory's across worlds. That being said, I have had a handful of unexplained cases similar to yours and cannot rule out the possibility of a bug. 

- If you are still having this issue, please update us here or drop a message on our discord server in the #plugin-help channel and we will help troubleshoot this. https://discord.gg/AXm6uNfu
