### ISSUE TITLE
[Suggestion] Leaderboards

### ISSUE THREAD

**Issue by Exophobias** [BattlePlugins/BattleArena#136]
Hi there, is it possible for you to implement a leaderboard system for each kind of competition?

Thanks!

**Comment by supawiz6991** [comment]
HI,
So sorry for the long delay in responding to this. I missed the notification and just now saw it.

So, currently Leader boards can be set via signs for gamemode or by arena.

Expansion of the leader board system is unlikely at this time due to the current status of the plugin and the primary focus on the rewrite.

Here is the official status announcement from our discord:
Hey everyone. Just wanted to post a quick update from the BattlePlugins development team about the status of BattleArena. Many of you have been using the plugin while it has been in a less-than-ideal state while we work toward a rewrite of, what is at this point, an almost decade old legacy codebase.

BattleArena is still alive and the developers of the project are still around in Discord to provide support. However, due to other obligations and the small amount of developers we have, development of a new BattleArena is nearly at a halt. The only reason that BattleArena and its great community has lasted this long is from community members contributing and becoming part of our development team.

With that said, at this moment we are reaching out for anyone who is interested in contributing to the project to help us move it along. We are available for code reviews and more than willing to merge good contributions. Unfortunately we don't have great contribution guidelines, but you can keep track with issues and create pull requests at https://github.com/battlePlugins/BattleArena. Any pull request regardless of your Java experience would be reviewed. And again, we are still open to helping with any support requests and submitting tickets for existing bugs that may eventually get looked at. Thanks for all your support!

**Comment by clovisd** [comment]
Closing Issue, this is covered using BattleTracker that hooks into BA.

New BA and BT versions are in the works.
