### ISSUE TITLE
1.8 Suggestions: Regen, SB, Signs, Classes, etc

### ISSUE THREAD

**Issue by ghost** [BattlePlugins/BattleArena#22]
Better Regeneration System
I prefer either one that records all the actions that a player has done and reverts them after fifteen seconds after the game has ended, because of possible TNT explosions, or one that is based on AsyncWorldEdit, its an addon to WorldEdit allowing building, and regenerating to use less RAM and not freeze or crash the server, by only putting chunks and bits per tick instead of putting the whole thing. I use a very large map.

Better Scoreboard
I would like one that is very customizable, such as one that would show Wins, Losses, Money, and Players.

Customizable Signs
Although this is already possible to achieve by creating a game sign, deleting it, and putting another sign in the old one's exact location with your custom words, I would like it to be simpler and more customizable. There would also be variables, such as players and max players.

1.8 Title Support
If you win a game, there should be a 1.8 title saying, "You won!", or if someone else wins a game ,it would say, "<player> won!". Of course, this should be customizable.

Per-Arena Classes
Instead of having global classes, there should be classes per arena, because you don't want the diamond shovel from spleef being used for team deathmatch.

Waiting Room Items
There should be waiting room items. One should be something like a clock, that kicks you out of the game when right-clicked. The other lets you choose classes (Per-Arena Classes Advantages Here).

This would be THE PERFECT MINIGAMES/ARENA Plugin.

**Comment by Europia79** [comment]
@SmartSoda 

Thanks for the suggestions.

> Better Regeneration System

I definitely agree with this, because right now, WorldEdit is just NOT a good solution for resetting large arenas, because it will freeze the server.  I also had the same idea for a RamLogger that records block changes and reverts them after the arena.  Apparently, according to garbagemule, altho the idea is sound, the actual implementation can be tricky because of so many sources of block changes (or so he says).

But overall, I would like to implement SEVERAL DIFFERENT systems to revert block changes... That way, the server owner/admin can choose which one to use: whether it's (1) WorldEdit, (2) RamLogger, (3) AsycWorldEdit, or (4) other.

> because you don't want the diamond shovel from spleef being used for team deathmatch.

Can you elaborate on this ? Why don't you want a player to use a shovel in TDM ? If i understand correctly... if you're worried about them breaking blocks, you could just have the region protected ?

> Per-Arena Classes

At first glance, this sounds like a good idea... Because, (for example), we had someone create a Starwars minigame with classes for Rebel & Empire... So on the one hand, it kinda makes sense for class Rebel & class Empire to be specific to all arenas whose type is Starwars... But on the other hand, it means that it'll take longer to setup arenas (because you'll also have to setup corresponding classes too). 

And also, you run into the issue where some classes are duplicated across many different arena types. This duplication would be un-necessary and annoying.

So maybe a hybrid approach would be best ? Stay with global classes for servers that would rather use global classes... but at the same time, add an option for arena-specific-classes... Classes that are restricted to a specific ArenaType (you do mean per ArenaType, right ? Or really per physical Arena ? please clarify).

As it stands right now, I'm pretty sure for the waiting room for a particular arena, you could simply put class signs for only the classes that you want available ? (correct me if i'm wrong)

> 1.8 Title Support

I'm not familiar with this 1.8 feature... i'll have to look it up. Or if you want to elaborate, or you have some good links of information lying around ? If not, i'll look it up next week. Maybe Zach already knows about this tho ?

**Comment by SmartSoda** [comment]
Ok

We need Per-World Classes because if you have classes for spleef, and you have classes for team deathmatch, and since they are global, players in team deathmatch can access spleef classes, and spleef players can access deathmatch classes.
Although you can put signs, you have to give them the permission to use them. Giving them permission allows them to select classes not specified on the sign, by doing /arena class <___>.  I could use ServerSigns, because it allows temporary permissions when you click the sign and the command executes.
To rid of the annoying duplication of the classes per game, you could like in the classes.yml put an option under a class called allowedArenas.

Arena Regeneration
Yes. There are many sources of block breaking and events. You have to restore the items in the chests, restore player items, and like restore the blocks and such. Redstone I'm pretty sure is not a registered event in Bukkit, but thats where the Restore Block comes in. You HAVE to have a regen delay, because sometimes an arena ends while a TNT is going off, and you don't want to have the arena regenerated, and then the TNT blowing up.

Waiting Room and Spectator Items
This is the one you didn't comment on.
You could have items that let the player choose kit, or leave in the waiting room.
After a player dies, you should let players spectate the remainder of the game, and you should give them a leave tool, and a spectate tool.
It would be convienent if you could add a way in the config where players can choose their own tool IDs and names.

**Comment by SmartSoda** [comment]
I've managed to add a fast and efficient regeneration system using doCommands and CoreProtect.

**Comment by SmartSoda** [comment]
Selecting kits that cost you money, when you have no money, give you negative dollars. !!!

**Comment by lDucks** [comment]
@Europia79 @clovisd is this in the works? Completed? Any updates?

**Comment by Zach443** [comment]
@lDucks we are pretty much using these issues as a "to-do" list. As things get completed we can reference this issue number and the changes will show up in the feed here.

**Comment by Europia79** [comment]
@lDucks this guy has some good ideas. Thanks for reminding me.

As @Zach443 said, we try to follow the Bukkit contribution standards: Where in your commit message, you reference the Issue#. Then it automatically shows up here.

**Comment by SmartSoda** [comment]
Hello!
I'm back.
For arena regeneration, if you are having a hard time on this, I'd recommend CoreProtect. It's fast and efficent, covers everything like blocks and chests, and allows other plugins to use it as a dependency.

**Comment by Zach443** [comment]
@SmartSoda Thanks for those links! We have been exploring alternate options to WorldEdit for arena regeneration. I like the idea of using something like CoreProtect, the only problem is it would require users to also have the plugin running on the server to function. This could be problematic for users who either don't have enough power to run a block logger, or already use a different one.

**Comment by SmartSoda** [comment]
Don't worry! CoreProtect is the lightest logger out there, and I believe that it is even lighter than WorldEdit!

You could use it as a soft-dependency, and allow users to choose in some configuration their preferred reset method.

CoreProtect is the #1 Logger in Bukkit.

**Comment by Zach443** [comment]
Hmm, the soft dependency with a configurable option is a good idea. That would be much better than forcing users to have the plugin installed. I am a fan of CoreProtect as well, so I will definitely have to look into this.

**Comment by SmartSoda** [comment]
Also, another method is using AsyncWorldEdit alongside WorldEdit. AsyncWorldEdit allows editing large amounts of blocks at the same time by editing increments of blocks at a time.

API Docs: https://github.com/SBPrime/AsyncWorldEdit/wiki/API
Link: https://www.spigotmc.org/resources/asyncworldedit.327/

**Comment by SmartSoda** [comment]
I'd prefer CoreProtect, because AsyncWorldEdit takes some time to edit, while CoreProtect is way faster and efficient.

**Comment by SmartSoda** [comment]
Also with WorldEdit, there is a bug, if the server closes or crashes in mid-game, the map isn't restored, and the map is damaged.
Since CoreProtect is very very fast, please add a function so that all active games are closed properly during plugin unload.

**Comment by Zach443** [comment]
That same thing is possible with CoreProtect. If the server shuts down mid operation there is still a chance that the rollback will not finish properly.

**Comment by SmartSoda** [comment]
Isn't it possible to restore properly with the unload event?

**Comment by Redned235** [comment]
While this is a very old issue, I thought I'd reply as the vast majority of the following have been addressed with the rewrite.
 
- Better Regeneration System: Today, WorldEdit is still the de-facto solution for world manipulation and as such, BattleArena only supports it. However, drop-in replacements like FastAsyncWorldEdit speed this up, and therefore arena restoration now takes no hit to the server.
- Better Scoreboard: This has been completed and scoreboard support is far more custoizable.
- Customizable Signs: This is perhaps the only feature missing, and is not planned to come back to BattleArena. Signs are a very legacy way of doing things today, with commands and/or NPCs being the more common approach. Using existing solutions, this can be achieved with BattleArena.
- 1.8 Title Support: Implemented, using the message action.
- Per-Arena classes: This can be achieved using the Vault action, by giving permissions for classes in the `on-join` action. 
- Waiting Room Items: This too is now possible with the rewrite.
