### ISSUE TITLE
Teleporting to top block after battle

### ISSUE THREAD

**Issue by CassandraWipf** [BattlePlugins/BattleArena#43]
Platform: Spigot
Battle Arena Version: 3.9.10.4
World Guard Version: 6.0.0-snapshot.1582-
World Edit Version:6.0;3342-78f975b9
Permission Plugin: zPermissions
Other Plugins: N/A

Description: When a player stands too close to a wall or in a two-block high area and jumping, they get teleported to the top block, which can take them outside of the map. Would there be a way to change it in the config where it teleports them back to where they were, and not to the top block.

Info needed for Replication: Standing in a two block tall area, jumping, and joining a battle, when teleported out, getting teleported on top of the block your head was touching.

**Comment by Europia79** [comment]
@CassandraWipf 

damn, that's a pretty ingenious exploit.

http://www.planetminecraft.com/project/socom-us-navy-seals-frostfire-replica-paintball-arena/

As an example, I'm showing you that really small map that I built, where it was very easy for players to jump outside of the map. What I did was: I setup invisible Multiverse-Portals on the surface of the ocean... So that anyone who jumped outside the map would just get teleported back inside.

Anyways, this is one possible solution. Do you have the Multiverse plugin on your server ?

http://dev.bukkit.org/bukkit-plugins/multiverse-portals/

Another option would be to surround the map with lava or invisible blocks.

I really don't think that BattleArena can provide a solution for this because alls we're doing is player.teleport(location) 

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Entity.html#teleport(org.bukkit.Location)

So... we're saving the correct location, and teleporting them there... it's just that the Minecraft code has this edge case that creates the exploit.

**Comment by Zach443** [comment]
@CassandraWipf Maybe this can be solved with the '''teleportYOffset''' option in the config. If you set it to a negative value maybe that will solve players from being able to glitch into the ceiling block. I would be careful with that though, as if you set it too high you make produce the opposite problem. If that does not work, than like Euro said, I think it's more of a problem with Minecraft than with BattleArena.
