### ISSUE TITLE
battlearena timings

### ISSUE THREAD

**Issue by tara81** [BattlePlugins/BattleArena#57]
/ba kick 
/arena commands
match ending is causing high timings.

   Pct Total    Pct Tick       Total          Avg    PerTick         Count      Event
 0.11%  1,920.45%     1.92 s       960.23 ms     0.0           0.0k     Command: ctf
  0.04% 1,440.24%     0.72 s       720.12 ms     0.0           0.0k     Command: hub
                                                                                                        (this command runs /ba kick)

BattleArena v3.9.9.18Total: 2.684 s Pct: 0.15%

   Pct Total    Pct Tick       Total          Avg    PerTick         Count      Event

```
   0.12%    1,452.32%     2.18 s       726.16 ms     0.0           0.0k     Task: Match$3(Single)

   0.02%     800.06%      0.40 s       400.03 ms     0.0           0.0k     Task:
```

Match$MatchCompleted$1(Single)

```
   0.00%       0.09%      0.04 s         0.04 ms     0.0           1.0k     Task: Countdown(Single)

   0.00%       0.00%      0.02 s         0.00 ms     0.3          11.2k     BASignListener::onPlayerInteract(PlayerInteractEvent)

   0.00%       2.63%      0.02 s         1.32 ms     0.0           0.0k     Task: PermissibleBase$RemoveAttachmentRunnable(Single)

   0.00%       8.40%      0.00 s         4.20 ms     0.0           0.0k     Task: EventScheduler$RunEvent(Single)
```

**Comment by tara81** [comment]
1.8.8 Spigot, 3.9.7.9 Battlearena, ArenaCTF 1.3.2 , Worldguard 6.1, Worldedit 6.1.

**Comment by Europia79** [comment]
your version of BattleArena doesn't even support WorldEdit 6.1. The minimum version that you need to support WE v6.1 is BattleArena v3.9.9.8

but i highly recommend updating the the latest version to get all the bug fixes.
http://dev.bukkit.org/bukkit-plugins/battlearena2/

What you are noticing are minor lag spikes everytime a match starts: It's just the processing power required to do this job. Which on your server takes less than a second (726 milliseconds).

Here's a guy who reported a similar issue:
http://dev.bukkit.org/bukkit-plugins/battlearena2/#c415
https://embed.gyazo.com/944303eb81e4c3c3e8ed20832ba09355.png
As you can see, your ```startMatch()``` is running 7 times longer than his... So, more powerful hardware like CPU could help.

i'm debugging now in order to see if there's any code that we can optimize.

Generally, it looks like it's doing a lot of hashmap lookups which are very fast.

But it looks like BattleArena is using reflection (which can be slow) here:
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/objects/victoryconditions/VictoryType.java#L71

So we might have to look into an alterntive solution, like using factories to create objects instead of reflection creating objects.

It looks like the MethodController is doing a TON of processing:
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/listeners/custom/MethodController.java#L296 

But the MethodController is setting up all the Bukkit & Arena Events for each MatchState... Alkarin's idea behind this was that eventho you're using a lot of processing to set things up, it makes things more efficient later on (as well as more customizable)... So that you don't get lag during the match.

Anyways, that's my evalution of what's going on inside ```Match$3```: The majority of the processing time is devoting to setting up Events in order to make things faster during the match. The reflection is tiny in comparison.

**Comment by tara81** [comment]
I dont use world edit for battlearena , but i did update to the latest version a few months ago .
