### ISSUE TITLE
The Rainbow Repository is down 

### ISSUE THREAD

**Issue by Rocologo** [BattlePlugins/BattleArena#87]
So Im not able to add BattleArena as a dependency for my plugin MobHunting

**Comment by Zach443** [comment]
That repo was hosted by @Europia79 , he should know what happened to it. In the meantime, you can clone this repository to your computer and just compile the plugin/add it to your local maven repository that way

**Comment by Rocologo** [comment]
Hi and thanks, yes I think I can do this on my laptop, but what do I do on my Jenkins server and my Artifactory server?

**Comment by Europia79** [comment]
Just install maven on your Jenkins server.

Btw, here are some example commands to add files to your local maven repository:
```mvn install:install-file -Dfile= -DgroupId= -DartifactId= -Dversion= -Dpackaging=jar -DcreateChecksum=true
su - jenkins -c 'mvn install:install-file -Dfile= -DgroupId= -DartifactId= -Dversion= -Dpackaging=jar -DcreateChecksum=true'
su - jenkins -c 'mvn install:install-file -Dfile=/var/minecraft/server/plugins/BattleArena.jar -DgroupId=mc.alk -DartifactId=BattleArena -Dversion=3.9.10.15 -Dpackaging=jar -DcreateChecksum=true'```

Hopefully I can get the rainbowcraft repository backup tomorrow. Thanks for letting me know.

**Comment by Rocologo** [comment]
I was not that east because then I was missing some BattleArenaLibaries, so I gave up and waited for you to fix the repository.

I can see its up again I my plugin complies fine again :-)

**Comment by Europia79** [comment]
https://github.com/BattlePlugins/BattleArena/blob/master/pom.xml#L64-L67
https://github.com/BattlePlugins/BattleBukkitLib
https://github.com/BattlePlugins/BattleBukkitLib/blob/master/pom.xml#L15-L34
https://github.com/BattlePlugins/BattleBukkitLib/tree/master/modules

Oh god, yeah, BattleBukkitLib dependency is almost impossible to build because it requires 20 different versions of Craftbukkit: 1.2.5 to 1.9

http://rainbowcraft.sytes.net/maven/repository/org/bukkit/craftbukkit/

This should probably be mirrored. In case the rainbowcraft repository every goes down again.

http://rainbowcraft.sytes.net/maven/repository/org/bukkit/fair-use.txt
